version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: watermark-backend-dev
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_outputs:/app/outputs
      - backend_logs:/app/logs
    networks:
      - watermark-network
    ports:
      - "5001:5001"
    command: ["python", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: watermark-frontend-dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - watermark-network
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  backend_uploads:
    driver: local
  backend_outputs:
    driver: local
  backend_logs:
    driver: local

networks:
  watermark-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
